import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Web3Provider } from "../components/Web3Provider";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
          {children}
          <Analytics />
          <SpeedInsights />
        </Web3Provider>
      </body>
    </html>
  );
}
